/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MailOdds.Model;
using MailOdds.Client;
using System.Reflection;

namespace MailOdds.Test.Model
{
    /// <summary>
    ///  Class for testing CreateJobFromS3Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateJobFromS3RequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateJobFromS3Request
        //private CreateJobFromS3Request instance;

        public CreateJobFromS3RequestTests()
        {
            // TODO uncomment below to create an instance of CreateJobFromS3Request
            //instance = new CreateJobFromS3Request();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateJobFromS3Request
        /// </summary>
        [Fact]
        public void CreateJobFromS3RequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateJobFromS3Request
            //Assert.IsType<CreateJobFromS3Request>(instance);
        }

        /// <summary>
        /// Test the property 'S3Key'
        /// </summary>
        [Fact]
        public void S3KeyTest()
        {
            // TODO unit test for the property 'S3Key'
        }

        /// <summary>
        /// Test the property 'Dedup'
        /// </summary>
        [Fact]
        public void DedupTest()
        {
            // TODO unit test for the property 'Dedup'
        }
    }
}
