// <auto-generated>
/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;

using MailOdds.Client;

namespace MailOdds.Model
{
    /// <summary>
    /// Bulk jobs use the account&#39;s default validation policy. To use a specific policy, set it as default via the Policies API.
    /// </summary>
    public partial class CreateJobRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateJobRequest" /> class.
        /// </summary>
        /// <param name="emails">List of emails to validate</param>
        /// <param name="dedup">Remove duplicate emails (default to false)</param>
        /// <param name="metadata">Custom metadata for the job</param>
        /// <param name="webhookUrl">URL for completion webhook</param>
        /// <param name="idempotencyKey">Unique key for idempotent requests</param>
        [JsonConstructor]
        public CreateJobRequest(List<string> emails, Option<bool?> dedup = default, Option<Object?> metadata = default, Option<string?> webhookUrl = default, Option<string?> idempotencyKey = default)
        {
            Emails = emails;
            DedupOption = dedup;
            MetadataOption = metadata;
            WebhookUrlOption = webhookUrl;
            IdempotencyKeyOption = idempotencyKey;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// List of emails to validate
        /// </summary>
        /// <value>List of emails to validate</value>
        [JsonPropertyName("emails")]
        public List<string> Emails { get; set; }

        /// <summary>
        /// Used to track the state of Dedup
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DedupOption { get; private set; }

        /// <summary>
        /// Remove duplicate emails
        /// </summary>
        /// <value>Remove duplicate emails</value>
        [JsonPropertyName("dedup")]
        public bool? Dedup { get { return this.DedupOption; } set { this.DedupOption = new(value); } }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> MetadataOption { get; private set; }

        /// <summary>
        /// Custom metadata for the job
        /// </summary>
        /// <value>Custom metadata for the job</value>
        [JsonPropertyName("metadata")]
        public Object? Metadata { get { return this.MetadataOption; } set { this.MetadataOption = new(value); } }

        /// <summary>
        /// Used to track the state of WebhookUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WebhookUrlOption { get; private set; }

        /// <summary>
        /// URL for completion webhook
        /// </summary>
        /// <value>URL for completion webhook</value>
        [JsonPropertyName("webhook_url")]
        public string? WebhookUrl { get { return this.WebhookUrlOption; } set { this.WebhookUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of IdempotencyKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdempotencyKeyOption { get; private set; }

        /// <summary>
        /// Unique key for idempotent requests
        /// </summary>
        /// <value>Unique key for idempotent requests</value>
        [JsonPropertyName("idempotency_key")]
        public string? IdempotencyKey { get { return this.IdempotencyKeyOption; } set { this.IdempotencyKeyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateJobRequest {\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("  Dedup: ").Append(Dedup).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("  IdempotencyKey: ").Append(IdempotencyKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateJobRequest" />
    /// </summary>
    public class CreateJobRequestJsonConverter : JsonConverter<CreateJobRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateJobRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateJobRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> emails = default;
            Option<bool?> dedup = default;
            Option<Object?> metadata = default;
            Option<string?> webhookUrl = default;
            Option<string?> idempotencyKey = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "emails":
                            emails = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "dedup":
                            dedup = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "metadata":
                            metadata = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "webhook_url":
                            webhookUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "idempotency_key":
                            idempotencyKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!emails.IsSet)
                throw new ArgumentException("Property is required for class CreateJobRequest.", nameof(emails));

            if (emails.IsSet && emails.Value == null)
                throw new ArgumentNullException(nameof(emails), "Property is not nullable for class CreateJobRequest.");

            if (dedup.IsSet && dedup.Value == null)
                throw new ArgumentNullException(nameof(dedup), "Property is not nullable for class CreateJobRequest.");

            if (metadata.IsSet && metadata.Value == null)
                throw new ArgumentNullException(nameof(metadata), "Property is not nullable for class CreateJobRequest.");

            if (webhookUrl.IsSet && webhookUrl.Value == null)
                throw new ArgumentNullException(nameof(webhookUrl), "Property is not nullable for class CreateJobRequest.");

            if (idempotencyKey.IsSet && idempotencyKey.Value == null)
                throw new ArgumentNullException(nameof(idempotencyKey), "Property is not nullable for class CreateJobRequest.");

            return new CreateJobRequest(emails.Value!, dedup, metadata, webhookUrl, idempotencyKey);
        }

        /// <summary>
        /// Serializes a <see cref="CreateJobRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createJobRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateJobRequest createJobRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createJobRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateJobRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createJobRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateJobRequest createJobRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createJobRequest.Emails == null)
                throw new ArgumentNullException(nameof(createJobRequest.Emails), "Property is required for class CreateJobRequest.");

            if (createJobRequest.MetadataOption.IsSet && createJobRequest.Metadata == null)
                throw new ArgumentNullException(nameof(createJobRequest.Metadata), "Property is required for class CreateJobRequest.");

            if (createJobRequest.WebhookUrlOption.IsSet && createJobRequest.WebhookUrl == null)
                throw new ArgumentNullException(nameof(createJobRequest.WebhookUrl), "Property is required for class CreateJobRequest.");

            if (createJobRequest.IdempotencyKeyOption.IsSet && createJobRequest.IdempotencyKey == null)
                throw new ArgumentNullException(nameof(createJobRequest.IdempotencyKey), "Property is required for class CreateJobRequest.");

            writer.WritePropertyName("emails");
            JsonSerializer.Serialize(writer, createJobRequest.Emails, jsonSerializerOptions);
            if (createJobRequest.DedupOption.IsSet)
                writer.WriteBoolean("dedup", createJobRequest.DedupOption.Value!.Value);

            if (createJobRequest.MetadataOption.IsSet)
            {
                writer.WritePropertyName("metadata");
                JsonSerializer.Serialize(writer, createJobRequest.Metadata, jsonSerializerOptions);
            }
            if (createJobRequest.WebhookUrlOption.IsSet)
                writer.WriteString("webhook_url", createJobRequest.WebhookUrl);

            if (createJobRequest.IdempotencyKeyOption.IsSet)
                writer.WriteString("idempotency_key", createJobRequest.IdempotencyKey);
        }
    }
}
