// <auto-generated>
/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailOdds.Client;

namespace MailOdds.Model
{
    /// <summary>
    /// GetPresignedUploadRequest
    /// </summary>
    public partial class GetPresignedUploadRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPresignedUploadRequest" /> class.
        /// </summary>
        /// <param name="filename">Original filename</param>
        /// <param name="contentType">File MIME type</param>
        [JsonConstructor]
        public GetPresignedUploadRequest(string filename, Option<string?> contentType = default)
        {
            Filename = filename;
            ContentTypeOption = contentType;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Original filename
        /// </summary>
        /// <value>Original filename</value>
        [JsonPropertyName("filename")]
        public string Filename { get; set; }

        /// <summary>
        /// Used to track the state of ContentType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContentTypeOption { get; private set; }

        /// <summary>
        /// File MIME type
        /// </summary>
        /// <value>File MIME type</value>
        [JsonPropertyName("content_type")]
        public string? ContentType { get { return this.ContentTypeOption; } set { this.ContentTypeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetPresignedUploadRequest {\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetPresignedUploadRequest" />
    /// </summary>
    public class GetPresignedUploadRequestJsonConverter : JsonConverter<GetPresignedUploadRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetPresignedUploadRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetPresignedUploadRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> filename = default;
            Option<string?> contentType = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "filename":
                            filename = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "content_type":
                            contentType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!filename.IsSet)
                throw new ArgumentException("Property is required for class GetPresignedUploadRequest.", nameof(filename));

            if (filename.IsSet && filename.Value == null)
                throw new ArgumentNullException(nameof(filename), "Property is not nullable for class GetPresignedUploadRequest.");

            if (contentType.IsSet && contentType.Value == null)
                throw new ArgumentNullException(nameof(contentType), "Property is not nullable for class GetPresignedUploadRequest.");

            return new GetPresignedUploadRequest(filename.Value!, contentType);
        }

        /// <summary>
        /// Serializes a <see cref="GetPresignedUploadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getPresignedUploadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetPresignedUploadRequest getPresignedUploadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getPresignedUploadRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetPresignedUploadRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getPresignedUploadRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetPresignedUploadRequest getPresignedUploadRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getPresignedUploadRequest.Filename == null)
                throw new ArgumentNullException(nameof(getPresignedUploadRequest.Filename), "Property is required for class GetPresignedUploadRequest.");

            if (getPresignedUploadRequest.ContentTypeOption.IsSet && getPresignedUploadRequest.ContentType == null)
                throw new ArgumentNullException(nameof(getPresignedUploadRequest.ContentType), "Property is required for class GetPresignedUploadRequest.");

            writer.WriteString("filename", getPresignedUploadRequest.Filename);

            if (getPresignedUploadRequest.ContentTypeOption.IsSet)
                writer.WriteString("content_type", getPresignedUploadRequest.ContentType);
        }
    }
}
