// <auto-generated>
/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using MailOdds.Client;

namespace MailOdds.Model
{
    /// <summary>
    /// ValidationResponseSuppressionMatch
    /// </summary>
    public partial class ValidationResponseSuppressionMatch : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationResponseSuppressionMatch" /> class.
        /// </summary>
        /// <param name="matched">matched</param>
        /// <param name="matchType">matchType</param>
        /// <param name="matchValue">matchValue</param>
        [JsonConstructor]
        public ValidationResponseSuppressionMatch(Option<bool?> matched = default, Option<MatchTypeEnum?> matchType = default, Option<string?> matchValue = default)
        {
            MatchedOption = matched;
            MatchTypeOption = matchType;
            MatchValueOption = matchValue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines MatchType
        /// </summary>
        public enum MatchTypeEnum
        {
            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            Email = 1,

            /// <summary>
            /// Enum Domain for value: domain
            /// </summary>
            Domain = 2
        }

        /// <summary>
        /// Returns a <see cref="MatchTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static MatchTypeEnum MatchTypeEnumFromString(string value)
        {
            if (value.Equals("email"))
                return MatchTypeEnum.Email;

            if (value.Equals("domain"))
                return MatchTypeEnum.Domain;

            throw new NotImplementedException($"Could not convert value to type MatchTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="MatchTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static MatchTypeEnum? MatchTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("email"))
                return MatchTypeEnum.Email;

            if (value.Equals("domain"))
                return MatchTypeEnum.Domain;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="MatchTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string MatchTypeEnumToJsonValue(MatchTypeEnum? value)
        {
            if (value == MatchTypeEnum.Email)
                return "email";

            if (value == MatchTypeEnum.Domain)
                return "domain";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of MatchType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MatchTypeEnum?> MatchTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets MatchType
        /// </summary>
        [JsonPropertyName("match_type")]
        public MatchTypeEnum? MatchType { get { return this.MatchTypeOption; } set { this.MatchTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Matched
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> MatchedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Matched
        /// </summary>
        [JsonPropertyName("matched")]
        public bool? Matched { get { return this.MatchedOption; } set { this.MatchedOption = new(value); } }

        /// <summary>
        /// Used to track the state of MatchValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MatchValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets MatchValue
        /// </summary>
        [JsonPropertyName("match_value")]
        public string? MatchValue { get { return this.MatchValueOption; } set { this.MatchValueOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationResponseSuppressionMatch {\n");
            sb.Append("  Matched: ").Append(Matched).Append("\n");
            sb.Append("  MatchType: ").Append(MatchType).Append("\n");
            sb.Append("  MatchValue: ").Append(MatchValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ValidationResponseSuppressionMatch" />
    /// </summary>
    public class ValidationResponseSuppressionMatchJsonConverter : JsonConverter<ValidationResponseSuppressionMatch>
    {
        /// <summary>
        /// Deserializes json to <see cref="ValidationResponseSuppressionMatch" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ValidationResponseSuppressionMatch Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> matched = default;
            Option<ValidationResponseSuppressionMatch.MatchTypeEnum?> matchType = default;
            Option<string?> matchValue = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "matched":
                            matched = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "match_type":
                            string? matchTypeRawValue = utf8JsonReader.GetString();
                            if (matchTypeRawValue != null)
                                matchType = new Option<ValidationResponseSuppressionMatch.MatchTypeEnum?>(ValidationResponseSuppressionMatch.MatchTypeEnumFromStringOrDefault(matchTypeRawValue));
                            break;
                        case "match_value":
                            matchValue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (matched.IsSet && matched.Value == null)
                throw new ArgumentNullException(nameof(matched), "Property is not nullable for class ValidationResponseSuppressionMatch.");

            if (matchType.IsSet && matchType.Value == null)
                throw new ArgumentNullException(nameof(matchType), "Property is not nullable for class ValidationResponseSuppressionMatch.");

            if (matchValue.IsSet && matchValue.Value == null)
                throw new ArgumentNullException(nameof(matchValue), "Property is not nullable for class ValidationResponseSuppressionMatch.");

            return new ValidationResponseSuppressionMatch(matched, matchType, matchValue);
        }

        /// <summary>
        /// Serializes a <see cref="ValidationResponseSuppressionMatch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationResponseSuppressionMatch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ValidationResponseSuppressionMatch validationResponseSuppressionMatch, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, validationResponseSuppressionMatch, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ValidationResponseSuppressionMatch" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="validationResponseSuppressionMatch"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ValidationResponseSuppressionMatch validationResponseSuppressionMatch, JsonSerializerOptions jsonSerializerOptions)
        {
            if (validationResponseSuppressionMatch.MatchValueOption.IsSet && validationResponseSuppressionMatch.MatchValue == null)
                throw new ArgumentNullException(nameof(validationResponseSuppressionMatch.MatchValue), "Property is required for class ValidationResponseSuppressionMatch.");

            if (validationResponseSuppressionMatch.MatchedOption.IsSet)
                writer.WriteBoolean("matched", validationResponseSuppressionMatch.MatchedOption.Value!.Value);

            var matchTypeRawValue = ValidationResponseSuppressionMatch.MatchTypeEnumToJsonValue(validationResponseSuppressionMatch.MatchTypeOption.Value!.Value);
            writer.WriteString("match_type", matchTypeRawValue);
            if (validationResponseSuppressionMatch.MatchValueOption.IsSet)
                writer.WriteString("match_value", validationResponseSuppressionMatch.MatchValue);
        }
    }
}
