/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using MailOdds.Api;
using MailOdds.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace MailOdds.Test.Api
{
    /// <summary>
    ///  Class for testing SystemApi
    /// </summary>
    public sealed class SystemApiTests : ApiTestsBase
    {
        private readonly ISystemApi _instance;

        public SystemApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISystemApi>();
        }

        /// <summary>
        /// Test GetTelemetrySummary
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetTelemetrySummaryAsyncTest()
        {
            Client.Option<string> window = default!;
            var response = await _instance.GetTelemetrySummaryAsync(window);
            var model = response.Ok();
            Assert.IsType<TelemetrySummary>(model);
        }

        /// <summary>
        /// Test HealthCheck
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task HealthCheckAsyncTest()
        {
            var response = await _instance.HealthCheckAsync();
            var model = response.Ok();
            Assert.IsType<HealthCheck200Response>(model);
        }
    }
}
