/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSendingDomain201Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSendingDomain201ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSendingDomain201Response
        //private CreateSendingDomain201Response instance;

        public CreateSendingDomain201ResponseTests()
        {
            // TODO uncomment below to create an instance of CreateSendingDomain201Response
            //instance = new CreateSendingDomain201Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSendingDomain201Response
        /// </summary>
        [Fact]
        public void CreateSendingDomain201ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSendingDomain201Response
            //Assert.IsType<CreateSendingDomain201Response>(instance);
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
    }
}
