/*
 * MailOdds Email Validation API
 *
 * MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@mailodds.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SendingDomain
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendingDomainTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendingDomain
        //private SendingDomain instance;

        public SendingDomainTests()
        {
            // TODO uncomment below to create an instance of SendingDomain
            //instance = new SendingDomain();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendingDomain
        /// </summary>
        [Fact]
        public void SendingDomainInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendingDomain
            //Assert.IsType<SendingDomain>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'DomainType'
        /// </summary>
        [Fact]
        public void DomainTypeTest()
        {
            // TODO unit test for the property 'DomainType'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'DkimSelector'
        /// </summary>
        [Fact]
        public void DkimSelectorTest()
        {
            // TODO unit test for the property 'DkimSelector'
        }

        /// <summary>
        /// Test the property 'DnsRecords'
        /// </summary>
        [Fact]
        public void DnsRecordsTest()
        {
            // TODO unit test for the property 'DnsRecords'
        }

        /// <summary>
        /// Test the property 'BimiSvgUrl'
        /// </summary>
        [Fact]
        public void BimiSvgUrlTest()
        {
            // TODO unit test for the property 'BimiSvgUrl'
        }

        /// <summary>
        /// Test the property 'BimiVmcUrl'
        /// </summary>
        [Fact]
        public void BimiVmcUrlTest()
        {
            // TODO unit test for the property 'BimiVmcUrl'
        }

        /// <summary>
        /// Test the property 'BimiEnabled'
        /// </summary>
        [Fact]
        public void BimiEnabledTest()
        {
            // TODO unit test for the property 'BimiEnabled'
        }

        /// <summary>
        /// Test the property 'ForwardRepliesTo'
        /// </summary>
        [Fact]
        public void ForwardRepliesToTest()
        {
            // TODO unit test for the property 'ForwardRepliesTo'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
